server.port: 8080

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always
  h2.console.enabled: true

  flyway:
    enabled: true
    locations: classpath:/db/migration

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type: INFO
      orm.jdbc.bind: TRACE