server.port: 8080

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always
  datasource:
#    todo delete
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:cgb
    username: cgb
    password: cgb
  h2.console.enabled: true

  flyway:
    enabled: true
    locations: classpath:/db/migration

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type: INFO
      orm.jdbc.bind: TRACE