CREATE TABLE IF NOT EXISTS landmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  city VARCHAR(64),
  name VARCHAR(64) NOT NULL,
  category VARCHAR(64) NOT NULL,
  location_lat FLOAT NOT NULL,
  location_lon FLOAT NOT NULL,
  average_rating FLOAT,
  CONSTRAINT pk_landmark PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rating_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  rating FLOAT NOT NULL,
  landmark_id BIGINT NOT NULL,
  CONSTRAINT pk_rating PRIMARY KEY (id),
  CONSTRAINT fk_rating_landmark_id FOREIGN KEY(landmark_id) REFERENCES landmarks(id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR NOT NULL,
  landmark_id BIGINT NOT NULL,
  CONSTRAINT pk_comment PRIMARY KEY (id),
  CONSTRAINT fk_comment_landmark_id FOREIGN KEY(landmark_id) REFERENCES landmarks(id)
);

CREATE OR REPLACE FUNCTION distance(lat1 float, lon1 float, lat2 float, lon2 float)
    RETURNS float AS '
    declare
        dist float = 0;
        rad_lat1 float;
        rad_lat2 float;
        theta float;
        rad_theta float;
    BEGIN
        IF lat1 = lat2 AND lon1 = lon2
        THEN
            RETURN dist;
        ELSE
            -- переводим градусы широты в радианы
            rad_lat1 = pi() * lat1 / 180;
            -- переводим градусы долготы в радианы
            rad_lat2 = pi() * lat2 / 180;
            -- находим разность долгот
            theta = lon1 - lon2;
            -- переводим градусы в радианы
            rad_theta = pi() * theta / 180;
            -- находим длину ортодромии
            dist = sin(rad_lat1) * sin(rad_lat2) + cos(rad_lat1) * cos(rad_lat2) * cos(rad_theta);

            IF dist > 1
                THEN dist = 1;
            END IF;

            dist = acos(dist);
            -- переводим радианы в градусы
            dist = dist * 180 / pi();
            -- переводим градусы в километры
            dist = dist * 60 * 1.8524;

            RETURN dist;
        END IF;
    END;
' LANGUAGE PLPGSQL;
