CREATE TABLE IF NOT EXISTS landmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  city VARCHAR(64),
  name VARCHAR(64) NOT NULL,
  category VARCHAR(64) NOT NULL,
  location_lat FLOAT NOT NULL,
  location_lon FLOAT NOT NULL,
  average_rating FLOAT,
  CONSTRAINT pk_landmark PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rating_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  rating FLOAT NOT NULL,
  landmark_id BIGINT NOT NULL,
  CONSTRAINT pk_rating PRIMARY KEY (id),
  CONSTRAINT fk_landmark_id FOREIGN KEY(landmark_id) REFERENCES landmarks(id)
);

/*CREATE TABLE IF NOT EXISTS games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  home_team_id BIGINT NOT NULL,
  away_team_id BIGINT NOT NULL,
  CONSTRAINT pk_game PRIMARY KEY (id),
  CONSTRAINT fk_home_team_id FOREIGN KEY(home_team_id) REFERENCES game_of_team(id),
  CONSTRAINT fk_away_team_id FOREIGN KEY(away_team_id) REFERENCES game_of_team(id),
  CONSTRAINT uq_home_team_id UNIQUE (home_team_id),
  CONSTRAINT uq_away_team_id UNIQUE (away_team_id)
);*/
--todo delete